### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/kpax/winfoom/FoomApplication 

### ISSUE THREAD

**Issue by johanvanoosterhout** [ecovaci/winfoom#47]
**Bug description**
launch.bat is unable to start

**To Reproduce**
1. when i start the launch.bat i get an error in de out.txt

**Expected behavior**
I expected the launch.bat to start

**Log**
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/kpax/winfoom/FoomApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**Context information:**
OS Windows Server 2016
Java version used, is the version included in the winfoom-windows version 3.1.1

**Comment by johanvanoosterhout** [comment]
Hello, I fixed it with the help of this bug

https://github.com/ecovaci/winfoom/issues/45

**Comment by ecovaci** [comment]
Fixed, please download again winfoom_windows.zip.
